### ISSUE TITLE
[PE-D] Incorrect display for Compatibility

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W10-3/tp#162]
When `add n/Zach e/123@gmail.com f/medicine m/Computer Science compat/1` is input, the display window shows that `Zach` has a compatibility of 92% instead of 1%

Input command:
![image.png](https://raw.githubusercontent.com/Zhouyirui/ped/main/files/b25d72bf-95fc-44af-8dcc-c09a90a13319.png)

Actual:
Compatibility of Zach is shown to be 92%
![image.png](https://raw.githubusercontent.com/Zhouyirui/ped/main/files/2bbd11b7-22df-4417-82e8-265030e10c8a.png)

Expected: CommandResult shows details of Zach with Compatibility of 1%

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: Zhouyirui/ped#4

**Comment by noobmaster19** [comment]
Can't be replicated. Closing this
